goapp:
  webserver:
    base:
      host: 0.0.0.0
      port: 9000
      useHostname: false
      basePath: /goapp
    
    http:
      readTimeout: 60s
      writeTimeout: 60s
      maxHeaderSizeMB: 1
      maxMultipartMemoryMB: 10
      idleTimeout: 60s
      gracefulShutdownTime: 5s

    log:
      enableAccessLog: true
      enableLogMiddleware: true
      enablePrintExposedRouter: true
  logging:
    base:
      reportCaller: false
    
    loggers:
      root: 6
      api: 1
    
    text:
      forceQuote: true
      disableColors: false
      fullTimestamp: true
    
    json:
      disableTimestamp: false
      disableHTMLEscape: false
      prettyPrint: false
    