goapp:
  webserver:
    host: 0.0.0.0
    port: 9000
    useHostname: false
    basePath: /
    readTimeout: 60
    writeTimeout: 60
    maxHeaderSizeMB: 1
    idleTimeout: 60
    gracefulShutdownTime: 5
    enableAccessLog: true
  logging:
    format: 0
    level: 6
    reportCaller: true
    disableTimestamp: false
    disableColors: false
    disableHTMLEscaping: false
    prettyPrint: false
    fullTimestamp: true
    forceQuote: true