goapp:
  webserver:
    host: 0.0.0.0
    port: 9000
    useHostname: false
  logging:
    format: 0
    level: 6
    reportCaller: true
    disableTimestamp: false
    disableColors: false
    disableHTMLEscaping: false
    prettyPrint: false
    fullTimestamp: true
    forceQuote: true